/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Anchor from '../packages/anchor/index.js';
import AnchorLink from '../packages/anchorLink/index.js';
import BackTop from '../packages/backTop/index.js';
import LineButton from '../packages/lineButton/index.js';
import DemoBlock from '../packages/demoBlock/index.js';
import TableSimple from '../packages/tableSimple/index.js';
import Link from '../packages/link/index.js';
import Breadcrumb from '../packages/breadcrumb/index.js';
import BreadcrumbItem from '../packages/breadcrumbItem/index.js';
import DatePick from '../packages/datePick/index.js';

const components = [
  Button,
  Anchor,
  AnchorLink,
  BackTop,
  LineButton,
  DemoBlock,
  TableSimple,
  Link,
  Breadcrumb,
  BreadcrumbItem,
  DatePick,
];

const install = function(Vue) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.1.14',
  install,
  Button,
  Anchor,
  AnchorLink,
  BackTop,
  LineButton,
  DemoBlock,
  TableSimple,
  Link,
  Breadcrumb,
  BreadcrumbItem,
  DatePick
};
